name: Docker Build and Push

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/huggingface-docker-webserver
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Pull built image for merge
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/huggingface-docker-webserver:latest

      - name: Export and import image to merge layers
        run: |
          # 创建容器并获取其ID
          container_id=$(docker create ghcr.io/${{ github.repository_owner }}/huggingface-docker-webserver:latest)
          # 导出容器的文件系统，并通过 docker import 生成合并层的新镜像
          docker export $container_id | docker import - ghcr.io/${{ github.repository_owner }}/huggingface-docker-webserver:merged
          docker rm $container_id

      - name: Push merged image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/huggingface-docker-webserver:merged
